name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and configure config.php
        run: |
          cp config.template.php config.php
          sed -i 's/%%DB_PASSWORD%%/${{ secrets.DB_PASSWORD }}/g' config.php
        shell: bash

      - name: Deploy to Rezoleo
        uses: rezoleo/rezoleo-deploy-action@v1
        with:
          sftp-key: ${{ secrets.DEPLOY_KEY }}
          sftp-user: climpact23
