name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Rezoleo
        uses: rezoleo/rezoleo-deploy-action@v2
        with:
          sftp-key: ${{ secrets.DEPLOY_KEY }}
          sftp-user: climpact23
