name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and configure config.php
        run: |
          cp config.template.php config.php
          sed -i 's/%%DB_PASSWORD%%/${{ secrets.DB_PASSWORD }}/g' config.php
        shell: bash

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude=".git/"
          remote_path: /home/projets/climpact23/writable/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: 8888
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}


      - name: Set permissions on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8888
          script: chown -R climpact23:projet /home/projets/climpact23/writable
