name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create and configure config.php
        run: |
          cp config.template.php config.php
          sed -i 's/%%DB_PASSWORD%%/${{ secrets.DB_PASSWORD }}/g' config.php
        shell: bash

      - name: Prepare clean folder
        run: |
          mkdir upload_clean
          shopt -s dotglob
          find . -mindepth 1 -maxdepth 1 ! -name upload_clean -exec cp -r {} upload_clean/ \;
          rm -rf upload_clean/.git

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Write SFTP private key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > id_rsa_climpact
          chmod 600 id_rsa_climpact

      - name: Deploy with lftp
        run: |
          cd upload_clean
          lftp -u climpact23,"" -e "set sftp:connect-program 'ssh -i ../id_rsa_climpact -o StrictHostKeyChecking=no -p 8888'; set ssl:verify-certificate no; mirror -R --delete --exclude-glob .git/ ./ /writable/; bye" sftp://sftp.rezoleo.fr
